//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public System.Guid PhotoId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid UserUserId { get; set; }
    
        public static Photo CreatePhoto(string name, string location, string description, string path, DateTime date, Guid idUser)
        {
            return new Photo
            {
                PhotoId = Guid.NewGuid(),
                Name = name,
                Location = location,
                Description = description,
                Path = path,
                Date = date,
                UserUserId = idUser
            };
        }
    }



}
